# Generated by Django 5.0 on 2023-12-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('email', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('Message', models.TextField()),
            ],
        ),
    ]
